TARGET1 = intel_bank_atm_login
TARGET2 = intel_bank_atm_check_balance
TARGET3 = intel_bank_atm_main
TARGET4 = intel_bank_atm_deposit
TARGET5 = intel_bank_atm_withdrawal
TARGET6 = intel_bank_atm_camera
TARGET7 = intel_bank_atm_end
TARGET8 = intel_bank_atm_transfer
TARGET9 = intel_bank_atm_client
include ./common.mk

